semaphore-protocol/website

versioned_docs/version-V2/what-is-semaphore.md

- Cleanup What is Semaphore.
- Separate audience concerns.
I expect this page to change with the design work.

docs: Cleanup What is Semaphore.

---

versioned_docs/version-V2/glossary.md
versioned_docs/version-V2/guides/groups.md

- Revise glossary entries.
- Add glossary entry.
- Add Groups guide content.

docs: Glossary and Groups guide

---

versioned_docs/version-V2/guides/anonymous-signaling.md
versioned_docs/version-V2/guides/proofs.md

Initial guide to explain how to generate and verify Semaphore proofs.
#3

docs: add guide for semaphore proofs

---

versioned_docs/version-V2/guides/proofs.md
versioned_docs/version-V2/what-is-semaphore.md

- Cleanup intro and Generate Proofs.
- Add links.

Docs proofs guide cleanup and linking

---

versioned_docs/version-V2/quick-setup.md

Cleanup, fixes, and comments for quick-setup.

Docs: fix quick setup

---

versioned_docs/version-V2/glossary.md
versioned_docs/version-V2/guides/groups.md

- Add incremental Merkle tree.
- Fix case
- Revise off-chain groups section.

docs: glossary, Groups guide

---

versioned_docs/version-V2/glossary.md

- Add relay definition to glossary.
- Use cases will expand on specific examples.

docs: add relay definition to glossary.

---

versioned_docs/version-V2/technical-reference/contracts.md

- Cleanup grammar.
- Add links.
- TODO: contracts feels like 1/2 reference, 1/2 guide. Verifiers, especially is more like a guide.

docs: contracts cleanup.

---

src/theme/Footer/index.tsx

Change Learn>Github link from Unirep to Semaphore URL

Change Learn>Github link from Unirep to Semaphore URL

---

versioned_docs/version-V2/quick-setup.md

Fix: minor typo

---

README.md

docs: adding GitPOAP link

---

versioned_docs/version-V2/quick-setup.md
versioned_docs/version-V2/use-cases/private-voting.md

Fix minor typos

---

versioned_docs/version-V2/technical-reference/contracts.md

Changed the links of SemaphoreCore.sol and SemaphoreGroups.sol contracts.
The previous links were broken, I just fixed to changed those to the correct ones.

fix contracts link

---

i18n/en/code.json
i18n/es/code.json
src/theme/Footer/index.tsx

This PR adds a Twitter link to the website footer.
#55

PSE Twitter link in the footer

---

i18n/es/docusaurus-plugin-content-docs/version-V3/glossary.md
i18n/es/docusaurus-plugin-content-docs/version-V3/what-is-semaphore.md
src/css/custom.scss
versioned_docs/version-V3/quick-setup.mdx

Add Docusaurus tabs to select package manager (npm and Yarn)
#42

Add tabs to select package manager

---

versioned_docs/version-V2/technical-reference/contracts.md

More fixes to broken links, following PR #48

more fixes to contracts links

---

i18n/es/docusaurus-plugin-content-docs/version-V3/deployed-contracts.md
versioned_docs/version-V3/deployed-contracts.md

This PR adds the Arbitrum contract addresses for Semaphore v3.
Closes #69

New arbitrum contract addresses

---

docusaurus.config.js

This PR sets the parameters for configuring the Algolia search bar.
#63 
In order to index the production website, we need to trigger a new crawl with the Algolia dashboard.

Algolia configuration

---

i18n/es/docusaurus-plugin-content-docs/version-V3/guides/proofs.md
src/pages/index.tsx
versioned_docs/version-V3/guides/proofs.md

This PR updates the documentation related to the `@semaphore-protocol/proof` library.

New Semaphore proof lib

---

i18n/es/docusaurus-plugin-content-docs/version-V3/guides/groups.md
i18n/es/docusaurus-plugin-content-docs/version-V3/guides/identities.md
i18n/es/docusaurus-plugin-content-docs/version-V3/guides/proofs.md
i18n/es/docusaurus-plugin-content-docs/version-V3/quick-setup.md
i18n/es/docusaurus-plugin-content-docs/version-V3/technical-reference/contracts.md
versioned_docs/version-V3/guides/groups.md
versioned_docs/version-V3/guides/identities.md

This PR adds some warnings to the guide to create and manage groups. In many cases we delegate choices to the developers, but it’s right to make them aware of the consequences.
Closes #66 
It is necessary to create an additional branch from the current one and create a PR for the Spanish translation of the text of the current PR.

Warnings for Semaphore groups

---

src/css/custom.scss

Change the styles of DocSearch and other elements.

Change DocSearch styles

---

i18n/es/docusaurus-plugin-content-docs/version-V3/quick-setup.mdx

Add tabs for package managers in `quick-setup.mdx` in the Spanish documentation

Add tabs for package managers in spanish doc

---

docusaurus.config.js
src/css/custom.scss
src/theme/Navbar/Search/index.tsx
src/theme/NavbarItem/index.tsx

This PR hides the search bar in the home page and the "Documentation" navbar button in the documentation page.
Closes #78

Dynamic visibility for navbar items

---

versioned_docs/version-V3/guides/groups.md

Just fixing Semaphore.sol link to github, the previous one is broken.

Fixing Semaphore.sol link

---

versioned_docs/version-V3/guides/groups.md

Fixing the SemaphoreGroups.sol github link, the previous one is broken.

Updating SemaphoreGroups.sol link

---

i18n/es/docusaurus-plugin-content-docs/version-V3/quick-setup.mdx
versioned_docs/version-V3/quick-setup.mdx

Fix npm deploy command and Semaphore contract addresses url in quick-setup.

Fix npm deploy command

---

versioned_docs/version-V3/technical-reference/contracts.md

Fix broken links in contracts.md

docs: fix links in contracts.md

---

.prettierignore
i18n/es/docusaurus-plugin-content-docs/version-V3.json
i18n/es/docusaurus-plugin-content-docs/version-V3/glossary.md
i18n/es/docusaurus-plugin-content-docs/version-V3/quick-setup.mdx
i18n/es/docusaurus-plugin-content-docs/version-V3/subgraph.md
i18n/es/docusaurus-plugin-content-docs/version-V3/technical-reference/circuits.md
i18n/es/docusaurus-plugin-content-docs/version-V3/what-is-semaphore.md
versioned_docs/version-V3/quick-setup.mdx

Update info to create a project using the CLI

Update CLI info in quick-setup

---

i18n/es/docusaurus-plugin-content-docs/version-V3/quick-setup.mdx
versioned_docs/version-V3/quick-setup.mdx

Add `.env` file in the output section in quick-setup.

Update quick-setup output section

---

i18n/es/docusaurus-plugin-content-docs/version-V3/guides/fetching-data.mdx
versioned_docs/version-V3/guides/fetching-data.mdx

Add guide to explain how to fetch on-chain group data

---

src/theme/Navbar/Search/index.tsx
src/theme/NavbarItem/index.tsx

This PR sets the correct conditions to show the right items in the navbar.

Correct conditions to show search bar

---

versioned_docs/version-V3/glossary.md

- Added the term semaphore "signal" compared to Circom to the glossary.
https://github.com/semaphore-protocol/website/issues/46

docs: wrote Signal explanation in glossary

---

versioned_docs/version-V3/resources.md

I added my Semaphore tutorial to resources.md

Added my Semaphore tutorial to resources.md
